# Generated by Django 3.2.13 on 2022-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_galleryimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
