# Generated by Django 3.2.13 on 2022-06-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_scheduler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scheduler',
            new_name='Schedule',
        ),
    ]
