# Generated by Django 3.2.13 on 2022-06-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_rename_scheduler_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
