# Generated by Django 3.2.13 on 2022-06-06 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0011_delete_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='customer',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_of',
            field=models.DateField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
    ]
