# Generated by Django 3.2.13 on 2022-06-06 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20220606_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_of',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
