# Generated by Django 3.2.13 on 2022-06-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_schedule_date_of'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
