# Generated by Django 3.2.13 on 2022-06-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20220606_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('timeslot', models.IntegerField(choices=[(0, '9am - 9.45am'), (1, '9.45am - 10.30am'), (2, '10.30am - 11.15am'), (3, '11.15am - 12pm'), (4, '12.30pm - 1.15pm'), (5, '1.15pm - 2pm'), (6, '2pm - 2.45pm'), (7, '2.45pm - 3.30pm'), (8, '3.30pm - 4.15pm'), (7, '4.15pm - 5pm')])),
                ('patient_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'timeslot')},
        ),
    ]
