# Generated by Django 3.2.13 on 2022-06-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20220607_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
    ]
