# Generated by Django 3.2.13 on 2022-06-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20220607_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='customer_name',
        ),
    ]
