# Generated by Django 3.2.13 on 2022-06-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_rename_patient_name_appointment_customer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Technician',
        ),
    ]
