# Generated by Django 3.2.13 on 2022-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_auto_20220607_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default='Please leave no spaces.', max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('nail_tech', 'date', 'timeslot', 'phone_number')},
        ),
    ]
