# Generated by Django 3.2.13 on 2022-06-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('nail_tech', 'date', 'timeslot')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
    ]
