# Generated by Django 3.2.13 on 2022-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_auto_20220608_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='customer_name',
            field=models.CharField(max_length=60),
        ),
    ]
