# Generated by Django 3.2.13 on 2022-06-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_remove_appointments_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='customer_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
