# Generated by Django 3.2.13 on 2022-06-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_appointments_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='customer_name',
        ),
    ]
